Update patch set 1
Patch Set 1:

The fail is 

FAILED: phosphor-version-software-manager@exe/image_manager.cpp.o 
c++ -Iphosphor-version-software-manager@exe -I. -I.. -I/usr/local/include -fdiagnostics-color=never -pipe -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wnon-virtual-dtor -Wextra -Wpedantic -Werror -std=c++17 -g -MD -MQ 'phosphor-version-software-manager@exe/image_manager.cpp.o' -MF 'phosphor-version-software-manager@exe/image_manager.cpp.o.d' -o 'phosphor-version-software-manager@exe/image_manager.cpp.o' -c ../image_manager.cpp
../image_manager.cpp:17:10: fatal error: xyz/openbmc_project/Software/Image/error.hpp: No such file or directory
   17 | #include <xyz/openbmc_project/Software/Image/error.hpp>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.

Which is caused by needed the PDI change

Patch-set: 1