clang-tidy: remove deprecated test
Clang 23 reports:

```
error: 'performance-faster-string-find' check is deprecated and will be
removed in a future release; consider using
'performance-prefer-single-char-overloads' instead
```

Change-Id: I1b2326195601712bd03683393fc5a481339ea5f0
Signed-off-by: Patrick Williams <patrick@stwcx.xyz>