meson: fix missing i2c header
Subproject builds result in the following compile error:
```
In file included from ../common/i2c/i2c.cpp:1:
../common/include/i2c/i2c.hpp:7:10: fatal error: sdbusplus/async.hpp: No such file or directory
    7 | #include <sdbusplus/async.hpp>
      |          ^~~~~~~~~~~~~~~~~~~~~
```

Add the missing dependency in the common/i2c subdirectory.

Signed-off-by: Patrick Williams <patrick@stwcx.xyz>
Change-Id: Ice1dd80fee70e57c6c4e5250d4c0f41e3122e2b9