meson: fix missing pldm header
Subproject builds fail with the following compile error:

```
c++ @eeprom-device/phosphor-eepromdevice-software-update.p/eeprom_device.cpp.o.rsp
In file included from ../common/include/device.hpp:3,
                 from ../eeprom-device/eeprom_device.hpp:3,
                 from ../eeprom-device/eeprom_device.cpp:1:
../common/pldm/package_parser.hpp:5:10: fatal error: libpldm/firmware_update.h: No such file or directory
    5 | #include <libpldm/firmware_update.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~
```

Fix by adding the appropriate libpldm dependency.

Signed-off-by: Patrick Williams <patrick@stwcx.xyz>
Change-Id: Ia79fe63c3929a62596ae292c352e488e1100eede