sync_watch: remove unused 'loop' member
Clang-19 warns about an unused member, which is indeed unused, so
remove it.

```
../sync_watch.hpp:73:15: error: private field 'loop' is not used [-Werror,-Wunused-private-field]
   73 |     sd_event& loop;
```

Signed-off-by: Patrick Williams <patrick@stwcx.xyz>
Change-Id: I3836822d8ebd4b9b1bb219be0583636ae8a47b96